### ISSUE TITLE
make it work on unix/all systems

### ISSUE THREAD

**Issue by fsmanuel** [halo/biosphere#3]
after your switch to `ruby_path` it should be easy to remove the os x dependency.

in ~/.biosphere/augmentations/bash_profile i added 

``` bash
export BIOSPHERE_RUBY="$HOME/.rbenv/shims/ruby"
```

and modified

``` ruby
def ruby_path
  return Pathname.new ENV['BIOSPHERE_RUBY'] if ENV['BIOSPHERE_RUBY']

  %w{ 2.1 2.0 1.9 1.8 }.each do |version|
    path = Pathname.new "/System/Library/Frameworks/Ruby.framework/Versions/#{version}"
    return path if path.exist?
  end
end
```

we could search for installed rubys as well but i like the idea of ENV more...

**Comment by halo** [comment]
Closing because we're now using `/usr/bin/ruby`
